import requests
import random

post_title = [
    "Cillum dolor elit minim consectetur.",
    "Labore pariatur.",
    "Labore minim laboris quis ex.",
    "Id do ut labore.",
    "Ex deserunt adipisicing.",
    "Irure voluptate est.",
    "Esse dolor est ad velit labore.",
    "Id sunt nostrud magna.",
    "Proident et nostrud.",
    "Laboris ad exercitation duis.",
]

post_content = [
    "Elit adipisicing laborum. Sit esse velit veniam culpa do nisi. Dolore consequat fugiat. Exercitation sunt duis voluptate deserunt. Ipsum aliquip ut cillum velit. Nulla irure aliqua aute. Dolore fugiat excepteur sit duis dolor. Id elit ipsum deserunt cupidatat et. Commodo Lorem veniam consectetur quis veniam. Sit aliqua Lorem nostrud laboris voluptate proident. Qui sint enim proident sint enim esse. Enim nulla sint. Commodo velit pariatur velit ex aute adipisicing. Est est excepteur qui. Anim nisi pariatur irure elit commodo. Anim exercitation dolore aliquip cupidatat deserunt. Aliquip nisi in nulla pariatur nulla esse. Velit anim enim qui. Cupidatat mollit commodo dolore voluptate deserunt reprehenderit. Proident amet dolor incididunt. Aliquip consectetur incididunt. Consectetur laboris irure consectetur adipisicing duis. Incididunt laborum aliquip. Ea excepteur aliqua culpa. Consectetur commodo veniam mollit minim reprehenderit. Reprehenderit anim ex est irure enim. Sit commodo velit sint do. Eiusmod est minim. Aute velit excepteur. Ea eu sint enim ad ullamco sunt. Consectetur cupidatat commodo elit enim. Eu laborum dolor tempor proident amet consequat. Consequat elit minim duis. Ut adipisicing sit. Consequat et magna deserunt tempor occaecat ad. Fugiat nostrud irure deserunt non. Veniam nulla exercitation. Sunt sint enim. Dolor reprehenderit elit elit. Officia eiusmod anim officia consequat. Nisi officia est mollit tempor anim consectetur. Enim mollit ad mollit sunt consequat enim.",
    "Eu eu nisi et nostrud aute. Laborum eu ea proident amet enim consequat. Incididunt aute reprehenderit. Officia cillum ea veniam. Ea enim proident. Reprehenderit sunt nulla consequat culpa labore ea. Quis id sint sit eu. Magna dolore adipisicing ut consectetur eiusmod. Magna cillum dolor ut ullamco velit Lorem. Ut Lorem ut. Ea ullamco est reprehenderit quis quis tempor. Adipisicing officia exercitation ea. Reprehenderit est ipsum. Do id id deserunt nulla. Do exercitation dolor aliquip officia consequat. Sit officia anim id ut nulla. Commodo ut id enim nisi nulla. Enim voluptate enim et et. Amet exercitation labore pariatur. Elit laboris elit officia enim duis fugiat. Est do velit anim excepteur deserunt sit. Irure culpa Lorem minim et sunt. Fugiat enim reprehenderit exercitation dolor. Esse ad sit voluptate eu ea. Consequat velit est. Enim eiusmod adipisicing qui. Enim magna voluptate enim dolor adipisicing sit. Ut voluptate in dolore consequat. Veniam non magna ad elit ea. Ex laboris fugiat. Et aliqua do officia deserunt Lorem ad. Aliquip voluptate duis duis duis officia do. Culpa aliqua velit ad sint. Tempor non pariatur sunt voluptate sit. Irure deserunt dolore in eu velit. Elit adipisicing elit. Ea eu voluptate sunt. Sint esse quis commodo aliquip eiusmod. Ut ullamco mollit minim fugiat nulla fugiat. Et commodo excepteur quis incididunt. Sit quis esse. Sint et nostrud. Laboris nisi pariatur anim labore velit eu. Consectetur consequat ut consequat duis exercitation. Cillum incididunt nisi. Laboris sit nisi deserunt proident. Magna consequat proident in adipisicing ex fugiat. Ipsum ullamco deserunt veniam sunt elit amet. Duis proident labore laborum dolor Lorem. Commodo nostrud esse sunt duis ad tempor.",
    "In labore ipsum amet dolore consectetur. Ea reprehenderit ad nostrud est officia. Magna adipisicing nostrud elit. Do sint reprehenderit minim ut. Dolore duis deserunt laborum adipisicing nostrud. Velit incididunt ut. Duis sint labore quis ad duis. Pariatur veniam id Lorem dolor Lorem. Ea magna ad culpa non magna anim. Quis aliquip do ad do aute. In ea exercitation exercitation occaecat culpa. Non nulla qui Lorem mollit officia. Sunt cillum sint tempor culpa veniam quis. In fugiat amet dolore. Aute adipisicing nisi laborum voluptate. Officia incididunt pariatur ipsum sint aute culpa. Consectetur occaecat enim excepteur. Esse sint amet cupidatat officia anim. Veniam eiusmod et duis sit excepteur. Laborum deserunt et eu aliquip excepteur ex. Consequat quis sit dolor ad aute est. Labore ad proident cupidatat nisi. Eiusmod laborum excepteur voluptate. Pariatur et qui fugiat esse. Do adipisicing velit quis dolore. Consequat eiusmod pariatur quis. Sint quis mollit non proident cupidatat enim. Consectetur duis tempor ad et quis minim. Sunt est magna elit. Ea qui deserunt ea laboris. Amet esse tempor. Consectetur dolore proident occaecat velit duis labore. Voluptate in do laboris commodo ad. Aliquip mollit sunt in culpa dolor. Commodo aliqua aliquip consectetur voluptate ullamco nisi. Non laboris occaecat in elit voluptate velit. Duis consequat reprehenderit excepteur in qui. Nostrud officia dolor exercitation. Minim aliquip dolore ullamco. Aliqua quis deserunt eiusmod aliquip ad velit. Dolore dolor quis. Ex exercitation amet. Nisi esse fugiat minim non amet. Mollit enim officia veniam sint et commodo. Proident nostrud duis. Quis sit ipsum do ut. Minim exercitation exercitation irure esse ut ea. Irure irure in ea fugiat qui. Magna mollit eu. Dolore incididunt amet occaecat.",
    "Officia consequat magna eu mollit adipisicing qui. Aute dolor ex in anim mollit. Reprehenderit laborum sit. Quis adipisicing est elit nulla in. Aute magna labore cupidatat. Est ea laborum irure deserunt. Est proident excepteur esse ex. Excepteur anim deserunt anim duis sint. Enim incididunt minim quis. Veniam nostrud labore exercitation occaecat. Non ea exercitation tempor Lorem. Exercitation minim dolor ea commodo. Aliquip deserunt nulla non. Lorem quis Lorem excepteur ipsum. Minim dolore officia. Qui amet dolor. Non qui nisi occaecat consequat. Laborum ullamco deserunt deserunt aliquip. Lorem minim voluptate. Consequat aliqua eu veniam officia. Labore consequat voluptate nulla officia ad tempor. Sunt culpa do in do. Lorem nulla officia. Est esse irure pariatur voluptate cupidatat. Consectetur do in et magna. Enim irure dolor cillum mollit ipsum consectetur. Enim magna nostrud. Mollit excepteur elit exercitation deserunt labore. Do reprehenderit incididunt fugiat ut nulla. Amet cupidatat Lorem aliquip fugiat culpa. Eiusmod amet veniam ea. Excepteur sit culpa. Adipisicing adipisicing laboris laborum eiusmod culpa. Voluptate id laboris adipisicing eiusmod exercitation. Sint labore voluptate magna officia nostrud. Aliqua irure laborum nisi in tempor. Incididunt ad enim dolore est dolor dolore. In culpa officia ex aliqua cillum cillum. Nostrud laboris excepteur voluptate. Proident qui minim magna laboris est. Quis eiusmod tempor anim.",
    "Sit qui qui Lorem consequat deserunt minim. Ipsum amet exercitation. Eiusmod excepteur tempor nostrud. Esse ad in occaecat fugiat dolor ut. Id voluptate exercitation est elit voluptate. Proident magna irure. Occaecat sint consectetur incididunt. Adipisicing consectetur ullamco mollit pariatur quis et. Do sunt occaecat ipsum consectetur. Irure culpa amet. Est dolore mollit veniam. Occaecat pariatur aliquip qui veniam irure. Amet consequat non aliquip officia eu ut. Irure et dolor. Ea officia cupidatat fugiat reprehenderit. Amet sint nostrud Lorem aliqua. Consectetur aliqua mollit magna Lorem labore aliquip. Sint fugiat laboris. Consectetur qui veniam consectetur velit. Exercitation minim deserunt minim fugiat enim. Fugiat quis nostrud minim ad. Aute est enim esse non culpa. Aute anim laboris voluptate. Non laboris reprehenderit. Officia ad excepteur reprehenderit. Quis ex cupidatat laborum laborum veniam ea. Reprehenderit irure proident. Non fugiat voluptate nostrud. Anim ex labore irure commodo officia fugiat. Sit officia eiusmod adipisicing magna. Commodo ex nostrud laboris id. Excepteur ut quis sint ea nostrud. Esse consectetur veniam dolore anim esse aute. Ipsum et duis tempor. Eiusmod laboris irure quis elit. Tempor ipsum ad nulla nostrud excepteur nisi. Reprehenderit veniam eu ullamco labore duis laboris. Adipisicing est do. Consequat consequat aliquip sint. Velit aliquip fugiat commodo adipisicing.",
    "Magna adipisicing irure laboris exercitation. Sunt nostrud deserunt. Et dolore duis commodo aliquip. Exercitation mollit nisi enim mollit consectetur. Excepteur pariatur ex. Quis commodo ea non non. Adipisicing adipisicing quis non sunt et veniam. Irure qui fugiat. Elit adipisicing nisi dolore excepteur aute ipsum. Cillum labore magna Lorem est. Pariatur reprehenderit quis irure nisi eu. Officia anim incididunt do reprehenderit qui. Sit dolore deserunt. Qui sit labore laborum laboris non. Dolore est labore sit incididunt proident quis. Nisi eu laboris quis dolore reprehenderit. Amet id ad velit incididunt duis anim. Excepteur cillum non. Aliqua mollit sunt adipisicing magna officia consectetur. Anim sint tempor occaecat laborum. Reprehenderit minim exercitation ipsum eiusmod anim adipisicing. Cillum velit magna id non ullamco. Ullamco deserunt pariatur amet veniam ut reprehenderit. Cillum qui elit velit aliquip. Id exercitation occaecat. Laboris enim dolor. Qui occaecat tempor amet. Incididunt do mollit ex excepteur aliqua incididunt. Deserunt nostrud ut cupidatat culpa adipisicing. Exercitation duis et aliquip amet ex laboris. Nisi cupidatat aliquip enim. Non eiusmod exercitation. Ut amet exercitation sunt. Magna magna occaecat esse. Elit magna nulla cupidatat. Anim fugiat ad. Aliquip id ex eu ipsum non aliqua. Fugiat laboris officia. Magna culpa eiusmod commodo incididunt. Duis culpa veniam cupidatat amet ullamco reprehenderit. Magna adipisicing elit. Consectetur mollit excepteur eiusmod eiusmod. Eu et irure elit ullamco. Adipisicing esse cillum.",
    "Esse commodo id elit non duis. Anim ex anim. Proident tempor labore esse non sit in. Sint quis eu. Anim anim consectetur duis laborum. Culpa sit minim adipisicing. Velit aliquip cupidatat ut aute veniam nisi. Et veniam pariatur. Magna qui aute. Sunt anim dolore officia labore magna. Consectetur incididunt aliquip incididunt consequat. Enim occaecat sunt ea laborum qui exercitation. Amet pariatur aliqua amet non. Lorem qui occaecat voluptate veniam esse aute. Id officia eu cupidatat. Mollit consectetur aute minim tempor ad incididunt. Minim eiusmod ipsum deserunt. Culpa non aliquip id laborum. Anim aute amet. Commodo incididunt qui. Tempor occaecat nisi non consectetur proident eiusmod. Eiusmod voluptate cillum nulla irure duis tempor. Eu laborum consequat excepteur. Commodo nostrud minim cillum incididunt labore. Proident sint nulla. Dolor ea anim. Mollit amet fugiat occaecat commodo officia enim. Velit Lorem cupidatat nulla dolor excepteur. Adipisicing proident voluptate aliquip cupidatat dolor voluptate. Nulla nulla eiusmod sit nulla. Do culpa dolor reprehenderit elit cupidatat in. Deserunt sit enim occaecat elit nulla fugiat. Aute ipsum in consectetur. Occaecat reprehenderit anim voluptate. Tempor id anim irure irure quis. Do elit qui cillum excepteur commodo. Lorem ut est dolor. Ex tempor dolor. Ullamco commodo mollit aliquip occaecat sit proident. Sit laborum sit ea. Consequat aliqua irure ullamco esse reprehenderit nisi. Sint enim adipisicing.",
    "Veniam exercitation ad eiusmod in. Sint esse deserunt. Lorem ut ad. Sit id ad in. Ullamco deserunt quis id. Ea deserunt quis eu fugiat. Irure exercitation irure sit in. Cillum fugiat esse ipsum enim. Velit veniam tempor. Consectetur ut cupidatat cillum magna labore cillum. Commodo commodo duis. Sunt mollit occaecat ut occaecat esse. Aute elit qui et ipsum amet duis. Nulla consectetur veniam labore. Exercitation labore occaecat labore aute anim do. Elit laboris non anim aliqua consequat. Consequat minim dolore quis sint. Ex magna labore excepteur est. Est tempor laborum aliquip consectetur est. Qui nisi culpa dolor mollit. Do exercitation enim esse sint sit in. Dolor sunt cupidatat esse. Culpa ullamco Lorem. Ad mollit adipisicing duis adipisicing. In eu velit anim sunt consectetur. Exercitation exercitation laborum exercitation sint. Sint in commodo elit velit sint. Voluptate adipisicing occaecat est. Reprehenderit voluptate est aliqua aliqua consequat voluptate. Eu eiusmod ex ea cupidatat nostrud veniam. Id dolore deserunt veniam excepteur eu laborum. Ut minim aute. Enim laboris consectetur id. Dolore voluptate Lorem irure. Eiusmod est duis nulla ad adipisicing minim. Labore do Lorem. Aliqua nisi et ea. Ipsum reprehenderit velit. Ea adipisicing fugiat sit dolore nostrud anim. Sunt tempor incididunt aliquip. In aute culpa labore mollit sunt. Lorem ut incididunt do. Tempor laborum laboris culpa. Do anim nisi. Cupidatat do enim irure non.",
    "Laboris voluptate aliqua cillum laborum. Sit officia duis amet veniam ipsum eiusmod. Incididunt duis dolore ea culpa. Magna reprehenderit laborum ea id. Velit laborum do laboris. Ad culpa dolor culpa. Voluptate ea Lorem occaecat irure aliquip. Ex irure ex irure. Officia nostrud velit ipsum est eiusmod. Mollit ea velit culpa. Amet duis incididunt. Laborum aliquip consequat culpa ea ut. Minim commodo eu elit excepteur aliquip. Aliquip mollit non ea. Ipsum nisi est magna. Pariatur do eu ea qui proident. Magna occaecat labore occaecat culpa nulla cillum. Nostrud tempor minim. Proident magna labore id. Qui proident aute irure. Laboris labore reprehenderit cillum minim ullamco pariatur. Duis sit labore anim et. Est veniam sit sit. Aliquip commodo in cupidatat. Fugiat culpa proident culpa amet minim. Id non qui. Esse amet consectetur fugiat deserunt. Id commodo sit. Est enim proident dolor. Aliqua ipsum mollit id eiusmod. Id ex culpa cupidatat laboris velit laborum. Excepteur magna est adipisicing exercitation. Do occaecat dolor. Fugiat ex commodo eu culpa labore consectetur. Dolor reprehenderit ut cillum elit ullamco. Aliqua incididunt nostrud proident. Cillum incididunt magna quis ut duis fugiat. Ex dolore ad amet. Aliqua elit occaecat irure aliquip commodo. Ipsum ad occaecat dolore. Pariatur commodo velit aliquip esse occaecat. Adipisicing esse et ullamco pariatur anim. Enim non nulla minim aliquip. Et proident enim. Reprehenderit cillum nisi ad enim quis.",
    "Sint do irure veniam deserunt. Cupidatat ex Lorem. Amet laborum reprehenderit dolor laboris ipsum. Cillum proident pariatur qui nostrud sit anim. Ut cillum do magna anim. Fugiat laboris id aute. Nisi fugiat veniam dolore cillum nisi. Culpa irure incididunt exercitation fugiat veniam. Deserunt officia cupidatat duis officia eiusmod. Fugiat anim dolor mollit laboris non. Qui dolore aute fugiat. Exercitation cupidatat culpa ut duis sit ad. Ut ut ex voluptate commodo mollit. Ullamco et tempor officia mollit sint eu. Cupidatat tempor sint Lorem esse. Id cillum cupidatat incididunt consectetur incididunt aliquip. Anim dolor exercitation adipisicing aliqua. Culpa pariatur id mollit adipisicing. Ex consectetur aute. Sunt quis tempor pariatur. Reprehenderit consectetur cupidatat occaecat exercitation occaecat. Aliquip cillum nostrud nisi velit. Culpa fugiat nisi dolore. Id deserunt sunt nulla id duis et. Non minim nostrud est. Ut nostrud ut. Laboris quis proident est id consequat excepteur. Aliquip eiusmod sit. Proident occaecat irure. Ut reprehenderit nisi Lorem tempor excepteur. Officia consequat est occaecat. Voluptate est sit cillum consectetur veniam. Nisi ex magna non proident. Amet adipisicing ad officia ut anim amet. Ad nisi officia deserunt. Amet aliqua laboris consectetur. Amet tempor aliquip. Velit consectetur culpa ipsum. Ex sunt sint consequat. Amet dolore adipisicing. Incididunt officia ullamco enim consectetur cupidatat. Culpa et amet magna nisi voluptate. Qui id id et nulla laborum. Velit exercitation qui exercitation enim. Anim et eiusmod aliqua. Et mollit magna consectetur.",
]

post_tags = [
    "Java",
    "Python",
    "C#",
    ".NET",
    "Web",
    "SpringBoot",
    "Node.js",
    "Rust",
    "Golang",
    "AI",
    "DeepSeek",
    "Gemini",
    "ChatGPT",
    "Unity",
    "Vue3",
]


def generate_post_data(key):
    return {
        "title": random.choice(post_title),
        "imageUrl": f"https://picsum.photos/400/300?random={key}",
        "content": random.choice(post_content),
        "heat": str(random.randint(100, 5000)),
        "comments": str(random.randint(100, 5000)),
        "likes": str(random.randint(100, 5000)),
        "tags": get_random_combination(post_tags),
    }


def get_random_combination(tags):
    k = random.randint(1, 3)
    return random.sample(tags, k)


def main():
    url = "http://localhost:3000/api/create"

    for i in range(12):
        try:
            response = requests.post(url, json=generate_post_data(i))
            print(f"第{i+1}次请求 - 状态码: {response.status_code}")
        except Exception as e:
            print(f"第{i+1}次请求失败: {str(e)}")


if __name__ == "__main__":
    main()
