
POST http://localhost:3000/api/create
Content-Type: application/json

{
  "title": "title",
  "imageUrl": "https://picsum.photos/400/300",
  "content": "文章正文文章正文文章正文",

  "heat": "0",
  "comments": "0",
  "likes": "0",
  "tags": []
}

###

POST http://localhost:3000/api/add-friend-link
Content-Type: application/json

{
  "title": "链接标题",
  "subtitle": "链接副标题",
  "link": "链接",
  "image": "图像"
}

###
GET http://localhost:3000/api/random-image HTTP/1.1
###
GET http://localhost:3000/api/random-image?source=pixiv HTTP/1.1
###
GET http://localhost:3000/api/random-image?source=bigknight53 HTTP/1.1

###

GET http://localhost:3000/api/posts?tags=AI,Web HTTP/1.1

###

GET http://localhost:3000/api/posts/67f4943b4b1cc548ca614b1e HTTP/1.1

###

GET http://localhost:3000/api/tags HTTP/1.1

